server:
  port: 3380

spring:
  application:
    # This ends up as the service name in zipkin
    name: testsleuthzipkin

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: false

management.tracing.sampling.probability: 1.0
